# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Vex"
license = "Themefisher license"
licenselink = "https://github.com/karju/vex-hugo/blob/master/LICENSE.md"
description = "Vex by Themefisher ported to Hugo"
homepage = "http://siteforthistheme.com/"
tags = ["onepage", "bootstrap", "product"]
features = ["onepage", "product"]
min_version = 0.15

[author]
  name = "Giacomo Mariani"
  homepage = "https://karju-dev.github.io"

# If porting an existing theme
[original]
  name = "Themefisher"
  homepage = "https://themefisher.com"
  repo = ""
